services:

  mongo-supplies-query:
    image: mongo:5.0
    container_name: mongo_supplies_query_db
    ports:
      - "27718:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  supplies-query:
    build: 
      context: .
      dockerfile: Dockerfile-Supplies-Query
    container_name: supplies-query-service
    depends_on:
      - mongo-supplies-query
    environment:
      - MONGO_HOST=mongo-supplies-query
      - MONGO_PORT=27017
    ports:
      - "3046:3046"
    command: node app.js
