services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  app:
    build: .
    container_name: python_magasin_app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./:/app
    command: python src/main.py
    stdin_open: true   # <- Permet d’ouvrir le stdin
    tty: true          # <- Alloue un terminal TTY