services:
  mongo-auth:
    image: mongo:5.0
    container_name: mongo_auth_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  mongo-stocks:
    image: mongo:5.0
    container_name: mongo_stocks_db
    ports:
      - "27118:27017" # port different pour docker-compose
    restart: always

  mongo-sales:
    image: mongo:5.0
    container_name: mongo_sales_db
    ports:
      - "27218:27017" # port different pour docker-compose
    restart: always

  mongo-supplies:
    image: mongo:5.0
    container_name: mongo_supplies_db
    ports:
      - "27318:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  auth:
    build: 
      context: ./src/backend/services/auth
      dockerfile: Dockerfile-Auth
    container_name: auth-service
    depends_on:
      - mongo-auth
    environment:
      - MONGO_HOST=mongo-auth
      - MONGO_PORT=27017
    ports:
      - "3010:3010"
    command: node app.js 

  stocks-1:
    build: 
      context: ./src/backend/services/stocks
      dockerfile: Dockerfile-Stocks
    container_name: stocks-service-1
    depends_on:
      - mongo-stocks
    environment:
      - MONGO_HOST=mongo-stocks
      - MONGO_PORT=27017
    ports:
      - "3020:3020"
    command: node app.js

  stocks-2:
    build: 
      context: ./src/backend/services/stocks
      dockerfile: Dockerfile-Stocks
    container_name: stocks-service-2
    depends_on:
      - mongo-stocks
    environment:
      - MONGO_HOST=mongo-stocks
      - MONGO_PORT=27017
    ports:
      - "3021:3020"  
    command: node app.js

  sales:
    build: 
      context: ./src/backend/services/sales
      dockerfile: Dockerfile-Sales
    container_name: sales-service
    depends_on:
      - mongo-sales
    environment:
      - MONGO_HOST=mongo-sales
      - MONGO_PORT=27017
    ports:
      - "3030:3030"
    command: node app.js

  supplies:
    build: 
      context: ./src/backend/services/supplies
      dockerfile: Dockerfile-Supplies
    container_name: supplies-service
    depends_on:
      - mongo-supplies
    environment:
      - MONGO_HOST=mongo-supplies
      - MONGO_PORT=27017
    ports:
      - "3040:3040"
    command: node app.js

  prometheus:
    image: prom/prometheus
    container_name: prometheus_server
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - krakend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  stocks-lb:
    image: nginx:latest
    container_name: stocks-loadbalancer
    ports:
      - "3022:3020"  # Redirige vers port 3020 interne de NGINX
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stocks-1
      - stocks-2

  krakend:
    image: devopsfaith/krakend:2.6
    container_name: krakend-gateway
    ports:
      - "80:80"
    volumes:
      - ./krakend:/etc/krakend
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - auth
      - stocks-1
      - stocks-2
      - sales
      - supplies
      - stocks-lb

volumes:
  grafana-storage:
