services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  app:
    build: .
    container_name: express-magasin-app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: node src/backend/app.js
    stdin_open: true   # <- Permet d’ouvrir le stdin
    tty: true          # <- Alloue un terminal TTY