services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  api1:
    build: .
    container_name: api1
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "3001:3001"
    command: node src/backend/app.js

  api2:
    build: .
    container_name: api2
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    command: node src/backend/app.js

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

  prometheus:
    image: prom/prometheus
    container_name: prometheus_server
    volumes:
      - ./src/backend/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: