services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  app:
    build: .
    container_name: express-magasin-app
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    command: node src/backend/app.js
    stdin_open: true   # <- Permet d’ouvrir le stdin
    tty: true          # <- Alloue un terminal TTY

  prometheus:
    image: prom/prometheus
    container_name: prometheus_server
    volumes:
      - ./src/backend/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: