global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'express-app'
    static_configs:
      - targets: ['auth-service:3010', 'stocks-service:3020', 'sales-service:3030', supplies-service:3040]
