services:

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # port AMQP
      - "15672:15672"

  notif:
    build: 
      context: .
      dockerfile: Dockerfile-Notification
    container_name: notif-service
    depends_on:
      - rabbitmq
    ports:
      - "3070:3070"
    command: node app.js
