services:

  mongo-stocks:
    image: mongo:5.0
    container_name: mongo_stocks_db
    ports:
      - "27118:27017" # port different pour docker-compose
    restart: always


  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  stocks-1:
    build: 
      context: ./src/backend/services/stocks
      dockerfile: Dockerfile-Stocks
    container_name: stocks-service-1
    depends_on:
      - mongo-stocks
    environment:
      - MONGO_HOST=mongo-stocks
      - MONGO_PORT=27017
    ports:
      - "3020:3020"
    command: node app.js

  stocks-2:
    build: 
      context: ./src/backend/services/stocks
      dockerfile: Dockerfile-Stocks
    container_name: stocks-service-2
    depends_on:
      - mongo-stocks
    environment:
      - MONGO_HOST=mongo-stocks
      - MONGO_PORT=27017
    ports:
      - "3021:3020"  
    command: node app.js

  

  
