services:

  mongo-supplies:
    image: mongo:5.0
    container_name: mongo_supplies_db
    ports:
      - "27318:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  supplies:
    build: 
      context: .
      dockerfile: Dockerfile-Supplies
    container_name: supplies-service
    depends_on:
      - mongo-supplies
    environment:
      - MONGO_HOST=mongo-supplies
      - MONGO_PORT=27017
    ports:
      - "3040:3040"
    command: node app.js
