services:

  mongo-sales:
    image: mongo:5.0
    container_name: mongo_sales_db
    ports:
      - "27218:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  sales:
    build: 
      context: .
      dockerfile: Dockerfile-Sales
    container_name: sales-service
    depends_on:
      - mongo-sales
    environment:
      - MONGO_HOST=mongo-sales
      - MONGO_PORT=27017
    ports:
      - "3030:3030"
    command: node app.js
