services:

  mongo-audit:
    image: mongo:5.0
    container_name: mongo_audit_db
    ports:
      - "27518:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # port AMQP
      - "15672:15672"

  supplies:
    build: 
      context: .
      dockerfile: Dockerfile-Audit
    container_name: audit-service
    depends_on:
      - mongo-audit
      - rabbitmq
    environment:
      - MONGO_HOST=mongo-audit
      - MONGO_PORT=27017
    ports:
      - "3060:3060"
    command: node app.js
