services:
  mongo-auth:
    image: mongo:5.0
    container_name: mongo_auth_db
    ports:
      - "27018:27017" # port different pour docker-compose
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always

  auth:
    build: 
      dockerfile: Dockerfile-Auth
    container_name: auth-service
    depends_on:
      - mongo-auth
    environment:
      - MONGO_HOST=mongo-auth
      - MONGO_PORT=27017
    ports:
      - "3010:3010"
    command: node app.js 
